# Generated by Django 4.2.4 on 2023-09-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_paymentgatewaysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
